name: router
description: router module for pokemon app.
version: 0.0.1
publish_to: none
environment:
  sdk: ">=2.19.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  home:
    path: ../features/home

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
