name: domain
description: domain module for pokemon app.
version: 0.0.1
publish_to: none
environment:
  sdk: ">=2.19.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  shared_dependencies:
    path: ../shared_dependencies
  mockito: ^5.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  json_serializable: ^6.6.1
  build_runner: ^2.3.3

flutter:
